name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Check Python syntax
        run: |
          python -m py_compile notebook.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flet==0.86.5
          python -m pip install flet-android-notifications==0.10.0
          python -m pip install certifi

      - name: First Flet build
        run: |
          flet build apk \
            --module-name notebook.py \
            --yes \
            --verbose \
            || true

      - name: Patch Android notifications
        run: |
          flet-android-notifications-patch \
            --project-root build/flutter

      - name: Final Flet APK build
        run: |
          flet build apk \
            --module-name notebook.py \
            --yes \
            --verbose

      - name: Find APK
        if: success()
        run: |
          echo "===== APK FILES ====="
          find build -type f -name "*.apk" -print

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: notebook-apk
          path: |
            build/apk/*.apk
            build/flutter/build/app/outputs/apk/release/*.apk
